---
- name: Instalar MariaDB Server e Cliente
  block:
    - apt:
        pkg:
          - mariadb-server
          - mariadb-client
          - python3-mysqldb
          - libmariadb-dev
        update_cache: yes
        state: present
  vars:
    wp_db_username: "wordpressuser"  # Substitua pelo nome de usuário desejado
    wp_db_password: "password"      # Substitua pela senha desejada
    wp_db_name: "wordpress"          # Substitua pelo nome do banco de dados desejado

  tasks:
      - name: Criar usuário MariaDB para WordPress
        mysql_user:
          name: "{{ wp_db_username }}"
          password: "{{ wp_db_password }}"
          priv: "{{ wp_db_name }}.*:ALL" # Ajustado para dar privilégios apenas no banco de dados do wordpress
          host: "%"
          state: present

      - name: Criar banco de dados WordPress
        mysql_db:
          name: "{{ wp_db_name }}"
          state: present

      - name: Reiniciar MariaDB para aplicar alterações
        service:
          name: mariadb
          state: restarted